services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    # 実行された全てのSQL文（SELECT、INSERT、UPDATE、CREATE TABLEなど）をログに出力する
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # コンテナ内のPostgreSQLのデータディレクトリとvolumeをマッピング

volumes:
  postgres_data:
    driver: local
